/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 3
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/lidar"
            imu_topic:  "/imu/data"
            camera_topic0: "/camera_0_CompressedImage"
            camera_topic1: "/camera_1_CompressedImage"
            camera_topic2: "/camera_2_CompressedImage"
            time_sync_en: false         # Time synchronization should remain off if not available.
            time_offset_lidar_to_imu: 0.0 # Based on the assumption in your JSON file.
        color_mapping0:
            K_camera: [960.0, 0.0, 960.0,
                    0.0, 960.0, 600.0,
                    0.0, 0.0, 1.0]
            D_camera: [0.0, 0.0, 0.0, 0.0, 0.0]
            time_offset_lidar_to_camera: 0.0
            extrinsic_T: [0.05, 0.0, -0.1]
            extrinsic_R: [ 0.0,  0.0,  1.0,
                        -1.0,  0.0,  0.0,
                        0.0, -1.0,  0.0 ]

        color_mapping1:
            K_camera: [960.0, 0.0, 960.0,
                    0.0, 960.0, 600.0,
                    0.0, 0.0, 1.0]
            D_camera: [0.0, 0.0, 0.0, 0.0, 0.0]
            time_offset_lidar_to_camera: 0.0
            extrinsic_T: [0.0, 0.05, -0.1]
            extrinsic_R: [ 1.0,  0.0,  0.0,
                        0.0,  1.0,  0.0,
                        0.0,  0.0,  1.0 ]

        color_mapping2:
            K_camera: [960.0, 0.0, 960.0,
                    0.0, 960.0, 600.0,
                    0.0, 0.0, 1.0]
            D_camera: [0.0, 0.0, 0.0, 0.0, 0.0]
            time_offset_lidar_to_camera: 0.0
            extrinsic_T: [0.0, -0.05, -0.1]
            extrinsic_R: [ 0.0,  0.0, -1.0,
                        1.0,  0.0,  0.0,
                        0.0,  1.0,  0.0 ]
        preprocess:
               
            lidar_type: 3
            scan_line: 32
            timestamp_unit: 3
            blind: 1.0

        mapping:
            acc_cov: 0.5
            gyr_cov: 0.5
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 150.0
            extrinsic_est_en: false
            extrinsic_T: [0.0, 0.0, 0.05]
            extrinsic_R: [1.0, 0.0, 0.0,
                          0.0, 1.0, 0.0,
                          0.0, 0.0, 1.0]

        publish:
            path_en: false
            scan_publish_en: true
            dense_publish_en: true
            scan_bodyframe_pub_en: true
            color_publish_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1